### ISSUE TITLE
Add common envelope benchmark dump files to server

### ISSUE THREAD

**Issue by themikelau** [phantomSPH/phantom-benchmarks#13]
Can these dumps for the commonenv benchmark be added to the web server? Thanks.

Dump 1: https://drive.google.com/file/d/1Z_FcoPkSvGJn7MY6gfG6Oo2vCJsnHZgD/view?usp=sharing
Dump 2: https://drive.google.com/file/d/1oKHQTVN2cC2fa3nd25gXKxCC58izn8ZJ/view?usp=sharing

**Comment by conradtchan** [comment]
Done:
http://data.phantom.cloud.edu.au/data/benchmarks/commonenv_00310
http://data.phantom.cloud.edu.au/data/benchmarks/commonenv_00311.ref

I only just noticed this because https://github.com/danieljprice/phantom/runs/5240217866 was failing. The benchmarks repo should run a test to catch these issues.

**Comment by themikelau** [comment]
Thanks Conrad!

**Comment by danieljprice** [comment]
this has been actioned
